package com.senla.rakickaya.courseplanner.api.data_exchange.enums;

public enum Intentions {
	GET_SORTED_COURSES_BY_START_DATE, GET_SORTED_COURSES_BY_COUNT_STUDENT, GET_SORTED_COURSES_BY_LECTOR_NAME, GET_SORTED_COURSES_BY_ALPH,
	GET_SORTED_LECTORS_BY_COUNT_STUDENT, GET_SORTED_LECTORS_BY_ALPH,
	GET_DETAILED_DESCRIPTION,
	GET_SORTED_TIME_TABLE_BY_DATE, GET_SORTED_TIME_TABLE_BY_ALPH,
	GET_SORTED_COURSES_BY_START_DATE_PARAM, GET_SORTED_COURSES_BY_COUNT_STUDENT_PARAM, GET_SORTED_COURSES_BY_LECTOR_NAME_PARAM, GET_SORTED_COURSES_BY_ALPH_PARAM,
	GET_SORTED_CURRENT_COURSES_BY_START_DATE, GET_SORTED_CURRENT_COURSES_BY_COUNT_STUDENT, GET_SORTED_CURRENT_COURSES_BY_LECTOR_NAME, GET_SORTED_CURRENT_COURSES_BY_ALPH, 	
	GET_TOTAL_COUNT_COURSES, GET_TOTAL_COUNT_STUDENTS, GET_TOTAL_COUNT_LECTORS,
	GET_LESSONS_BY_DATE,
	GET_PAST_COURSES, 
	ADD_COURSE, REMOVE_COURSE, ADD_LECTURE_TO_COURSE,REMOVE_LECTURE_FROM_COURSE,
	ADD_STUDENT, REMOVE_STUDENT, ADD_STUDENT_TO_COURSE,REMOVE_STUDENT_FROM_COURSE, 
	ADD_LECTOR, REMOVE_LECTOR, ADD_LECTOR_TO_COURSE,REMOVE_LECTOR_FROM_COURSE,
	CREATE_TIME_TABLE_FOR_LECTURE, REMOVE_TIME_TABLE_FOR_LECTURE,
	GET_ALL_STUDENTS, GET_ALL_LECTORS, GET_ALL_COURSES, GET_ALL_LECTURES,
	CLONE_COURSES, 
	EXPORT_COURSES, IMPORT_COURSES,
	EXPORT_STUDENTS, IMPORT_STUDENTS,
	EXPORT_LECTORS, IMPORT_LECTORS,
	EXPORT_TIME_TABLE, IMPORT_TIME_TABLE
}
